import './config.js';
import { api, cloudEnabled, loadCloudState, savePlaylist, getWorkspaceId } from './supabase.js';
import { requireSession,getStoredSession,signOut } from './auth.js';

let state={screens:[],media:[],playlists:[]};
const $=(s)=>document.querySelector(s), $$=(s)=>[...document.querySelectorAll(s)];
const icon=(name)=>`<i data-lucide="${name}"></i>`;
const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const safeUrl=value=>{try{const u=new URL(value,location.origin);return ['https:','http:','blob:'].includes(u.protocol)?esc(u.href):''}catch{return ''}};

function save(){render();}
function toast(msg){$('#toast-stack').insertAdjacentHTML('beforeend',`<div class="toast">${icon('circle-check')} ${esc(msg)}</div>`);lucide.createIcons();setTimeout(()=>$('.toast')?.remove(),2800)}
function empty(title,text){return `<div class="empty">${icon('monitor')}<strong>${title}</strong><span>${text}</span></div>`}
function render(){
  const online=state.screens.filter(x=>x.online).length;
  const usedBytes=state.media.reduce((total,item)=>total+(Number(item.size)||0),0),usedMb=usedBytes/1024/1024,limitMb=1024;
  $('#usage-label').textContent=`${usedMb<10?usedMb.toFixed(1):Math.round(usedMb)} MB de 1 GB`;$('#usage-bar').style.width=`${Math.min(100,usedMb/limitMb*100)}%`;
  $('#screen-count-nav').textContent=state.screens.length; $('#online-count').textContent=online;
  $('#stat-screens').textContent=state.screens.length; $('#stat-online').textContent=`${online} online agora`;
  $('#stat-media').textContent=state.media.length; $('#stat-playlists').textContent=state.playlists.length; $('#stat-hours').textContent='5s';
  $('#recent-screens').innerHTML=state.screens.slice(0,3).map(screenRow).join('')||empty('Nenhuma tela','Conecte sua primeira TV.');
  $('#screens-grid').innerHTML=state.screens.map(screenCard).join('')||empty('Nenhuma tela','Clique em Nova tela para começar.');
  $('#media-grid').innerHTML=state.media.map(mediaCard).join('')||empty('Biblioteca vazia','Adicione uma foto ou vídeo.');
  $('#playlists-grid').innerHTML=state.playlists.map(playlistCard).join('')||empty('Nenhuma playlist','Monte sua primeira sequência.');
  const activities=[];if(state.screens[0])activities.push(['monitor-check',`${esc(state.screens[0].name)} está ${state.screens[0].online?'online':'cadastrada'}`,'Status atual']);if(state.media[0])activities.push(['upload',`${esc(state.media[0].name)} está na biblioteca`,'Conteúdo']);if(state.playlists[0])activities.push(['list-video',`${esc(state.playlists[0].name)} está pronta para uso`,'Playlist']);
  $('#activity-list').innerHTML=activities.length?activities.map(a=>`<div class="activity-item"><div class="activity-icon">${icon(a[0])}</div><div><p>${a[1]}</p><small>${a[2]}</small></div></div>`).join(''):empty('Nenhuma atividade','As atualizações do seu espaço aparecerão aqui.');
  lucide.createIcons();
}
function screenRow(s){return `<div class="screen-row"><div class="screen-thumb"></div><div><strong>${esc(s.name)}</strong><small>${esc(s.location)} · ${esc(s.playlist)}</small></div><span class="${s.online?'online':'offline'}-badge">${s.online?'Online':'Offline'}</span></div>`}
function screenCard(s){return `<article class="screen-card" data-online="${s.online}" data-search="${esc(`${s.name} ${s.location}`.toLowerCase())}"><div class="screen-preview">${icon('monitor-play')}<span class="${s.online?'online':'offline'}-badge">${s.online?'Online':'Offline'}</span></div><div class="screen-info"><h3>${esc(s.name)}</h3><p>${esc(s.location)}</p><div class="screen-meta"><span>${esc(s.playlist)}</span><span>${esc(s.seen)}</span></div><div class="card-actions"><button class="secondary" data-card-action="edit-screen" data-id="${esc(s.id)}">Configurar TV</button><button class="danger-btn" data-card-action="remove-screen" data-id="${esc(s.id)}" aria-label="Apagar TV">${icon('trash-2')}</button></div></div></article>`}
function mediaCard(m){return `<article class="media-card" data-type="${m.type}" data-search="${esc(m.name.toLowerCase())}"><div class="media-thumb" style="background-image:url('${safeUrl(m.url)}')"><span class="type-chip">${icon(m.type==='video'?'video':'image')} ${m.type==='video'?'Vídeo':'Foto'}</span></div><div class="media-actions"><button data-card-action="remove-media" data-id="${esc(m.id)}" aria-label="Apagar conteúdo">${icon('trash-2')}</button></div><div class="media-info"><h3>${esc(m.name)}</h3><p>${m.type==='video'?'Duração automática':'Tempo definido na playlist'} · pronto para usar</p></div></article>`}
function playlistCard(p){const imgs=p.items.map(id=>state.media.find(m=>m.id===id)?.url).filter(Boolean);return `<article class="playlist-card"><div class="playlist-cover">${[0,1,2].map(i=>`<div style="background-image:url('${safeUrl(imgs[i]||'')}')"></div>`).join('')}</div><h3>${esc(p.name)}</h3><p>${p.items.length} conteúdo(s) · tempos personalizados</p><div class="playlist-foot"><span>${p.screens} tela(s) usando</span><div><button class="secondary" data-card-action="edit-playlist" data-id="${esc(p.id)}">Editar</button> <button class="danger-btn" data-card-action="remove-playlist" data-id="${esc(p.id)}" aria-label="Apagar playlist">${icon('trash-2')}</button></div></div></article>`}
function modal(title,subtitle,body,onSave,wide=false){const root=$('#modal-root');root.innerHTML=`<div class="modal ${wide?'wide':''}"><div class="modal-head"><div><h2>${title}</h2><p>${subtitle}</p></div><button class="modal-close">&times;</button></div><div class="modal-body">${body}</div><div class="modal-actions"><button class="secondary modal-close">Cancelar</button><button class="primary" id="modal-save">Salvar</button></div></div>`;root.classList.add('open');root.setAttribute('aria-hidden','false');$$('.modal-close').forEach(b=>b.onclick=closeModal);$('#modal-save').onclick=onSave;lucide.createIcons()}
function closeModal(){$('#modal-root').classList.remove('open');$('#modal-root').setAttribute('aria-hidden','true')}
function openConnect(){const paired=new URLSearchParams(location.search).get('pair');const code=paired||Math.random().toString(36).slice(2,8).toUpperCase();modal('Conectar nova tela','Abra o player na TV e use o código exibido.',`<div class="connect-steps"><div class="connect-step"><b>1</b>Na TV, acesse <strong>${location.origin}/tv</strong></div><div class="connect-step"><b>2</b>Leia o QR Code ou copie o código</div><div class="connect-step"><b>3</b>Dê um nome e escolha a playlist</div></div><div class="field"><label>Código da tela</label><input id="f-code" value="${esc(paired||'')}" placeholder="Ex.: ${code}" maxlength="6"></div><div class="field"><label>Nome desta tela</label><input id="f-name" maxlength="80" placeholder="Ex.: TV da recepção"></div><div class="field"><label>Local</label><input id="f-location" maxlength="120" placeholder="Ex.: Loja Centro"></div><div class="field"><label>Playlist inicial</label><select id="f-playlist"><option value="">Sem playlist</option>${state.playlists.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('')}</select></div>`,async()=>{const name=$('#f-name').value.trim(),deviceCode=$('#f-code').value.trim().toUpperCase(),locationName=$('#f-location').value.trim()||'Novo local';if(!name||!/^[A-Z0-9]{6}$/.test(deviceCode))return toast('Informe um código válido e o nome da tela');const playlistId=$('#f-playlist').value;try{if(cloudEnabled){await api.rpc('pair_screen',{p_device_code:deviceCode,p_name:name,p_location:locationName,p_playlist_id:playlistId||null});state=await loadCloudState()}else{state.screens.push({id:Date.now()+'',code:deviceCode,name,location:locationName,online:true,playlistId,playlist:state.playlists.find(p=>p.id===playlistId)?.name||'Sem playlist',seen:'Agora'})}save();closeModal();history.replaceState({},'',location.pathname);toast('Tela conectada com sucesso')}catch(e){toast(`Não foi possível conectar: ${e.message}`)}})}
function openMedia(){
  if(!cloudEnabled)return toast('Conecte o Supabase antes de enviar arquivos');
  modal('Adicionar conteúdo','Envie uma foto ou vídeo do seu dispositivo.',`<div class="dropzone" id="upload-zone">${icon('upload-cloud')}<strong>Escolha um arquivo</strong><span>JPG, PNG, WEBP, GIF, MP4 ou WEBM · até 500 MB</span><input id="f-file" type="file" accept="image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm" hidden></div><div class="field"><label>Nome do conteúdo</label><input id="f-name" placeholder="Será preenchido com o nome do arquivo"></div><div class="setting-note">Para TVs horizontais, recomendamos imagens 1920×1080 (proporção 16:9). O ajuste final pode ser escolhido na playlist.</div><br><div class="setting-note" id="file-status">Nenhum arquivo selecionado.</div>`,async()=>{
    const file=$('#f-file').files[0],name=$('#f-name').value.trim();
    if(!file)return toast('Selecione uma foto ou vídeo');
    try{const uploaded=await api.upload(file),type=file.type.startsWith('video/')?'video':'image';await api.insert('media_items',{workspace_id:getWorkspaceId(),created_by:getStoredSession().user.id,name:name||file.name.replace(/\.[^.]+$/,''),type,url:uploaded.url,storage_path:uploaded.path,size_bytes:file.size,duration_seconds:10});state=await loadCloudState();save();closeModal();toast('Conteúdo enviado com sucesso')}catch(e){toast(`Erro no envio: ${e.message}`)}
  });
  const zone=$('#upload-zone'),input=$('#f-file');zone.onclick=()=>input.click();input.onchange=()=>{const file=input.files[0];if(!file)return;$('#file-status').textContent=`${file.name} · ${(file.size/1024/1024).toFixed(1)} MB`;if(!$('#f-name').value)$('#f-name').value=file.name.replace(/\.[^.]+$/,'')};
}
function openPlaylist(existing){
  const p=existing||{name:'',items:[],durations:{},fits:{}};
  const cards=state.media.map(m=>`<div class="picker-item ${p.items.includes(m.id)?'selected':''}" data-id="${esc(m.id)}" data-type="${m.type}"><div class="picker-thumb" style="background-image:url('${safeUrl(m.url)}')"></div><p>${esc(m.name)}</p>${m.type==='image'?`<div class="picker-controls"><label class="picker-duration">Tempo <input type="number" min="1" max="3600" step="1" value="${Number(p.durations?.[m.id])||10}"> s</label><label class="picker-fit">Exibição <select><option value="cover" ${(p.fits?.[m.id]||'cover')==='cover'?'selected':''}>Preencher tela</option><option value="contain" ${p.fits?.[m.id]==='contain'?'selected':''}>Mostrar inteira</option><option value="fill" ${p.fits?.[m.id]==='fill'?'selected':''}>Esticar</option></select></label></div>`:'<small class="picker-auto">Duração automática</small>'}<span>${icon('check')}</span></div>`).join('');
  modal(existing?'Editar playlist':'Nova playlist','Defina o tempo e o enquadramento de cada imagem.',`<div class="field"><label>Nome da playlist</label><input id="f-name" maxlength="80" value="${esc(p.name)}" placeholder="Ex.: Ofertas do fim de semana"></div><div class="field"><label>Conteúdos</label><div class="media-picker">${cards}</div></div>`,async()=>{
    const name=$('#f-name').value.trim();if(!name)return toast('Dê um nome à playlist');
    const selected=$$('.picker-item.selected'),items=selected.map(x=>x.dataset.id);
    const durations=Object.fromEntries(selected.map(x=>[x.dataset.id,x.dataset.type==='image'?Math.min(3600,Math.max(1,Number(x.querySelector('.picker-duration input')?.value)||10)):10]));
    const fits=Object.fromEntries(selected.map(x=>[x.dataset.id,x.dataset.type==='image'?(x.querySelector('.picker-fit select')?.value||'cover'):'cover']));
    const playlist=existing||{id:'p'+Date.now(),screens:0};playlist.name=name;playlist.items=items;playlist.durations=durations;playlist.fits=fits;
    try{await savePlaylist(playlist);state=await loadCloudState();save();closeModal();toast('Playlist salva')}catch(e){toast(`Erro: ${e.message}`)}
  },true);
  $$('.picker-item').forEach(x=>x.onclick=e=>{if(e.target.closest('.picker-controls'))return;x.classList.toggle('selected')});
}
function openSettings(){modal('Minha conta','Dados do seu acesso ao TelaViva.',`<div class="field"><label>E-mail</label><input value="${esc(getStoredSession()?.user?.email||'')}" disabled></div><div class="field"><label>Plano atual</label><input value="${esc(state.workspace?.plan||'Starter')}" disabled></div><div class="setting-note">Seus dados e conteúdos são isolados dos demais clientes por políticas de segurança no banco.</div><br><button class="danger-btn" id="logout-button">Sair da conta</button>`,()=>closeModal());$('#logout-button').onclick=signOut}
$$('.nav-item[data-view]').forEach(b=>b.onclick=()=>{const id=b.dataset.view;$$('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(x=>x.classList.remove('active'));$(`#view-${id}`).classList.add('active');$('.sidebar').classList.remove('open');location.hash=id});
$$('[data-action="connect"]').forEach(b=>b.onclick=openConnect);$$('[data-action="media"]').forEach(b=>b.onclick=openMedia);$$('[data-action="playlist"]').forEach(b=>b.onclick=()=>openPlaylist());$$('[data-goto]').forEach(b=>b.onclick=()=>document.querySelector(`[data-view="${b.dataset.goto}"]`).click());$('#settings-btn').onclick=openSettings;$('.mobile-menu').onclick=()=>$('.sidebar').classList.toggle('open');
window.removeScreen=async id=>{if(!confirm('Remover esta TV?'))return;try{if(cloudEnabled)await api.remove('screens',`id=eq.${id}`);state.screens=state.screens.filter(x=>x.id!==id);save();toast('TV removida')}catch(e){toast(`Não foi possível remover: ${e.message}`)}};
window.removeMedia=async id=>{if(!confirm('Remover este conteúdo?'))return;try{const media=state.media.find(x=>x.id===id);if(cloudEnabled){if(media?.storagePath)await api.removeFile(media.storagePath);await api.remove('media_items',`id=eq.${id}`)}state.media=state.media.filter(x=>x.id!==id);save();toast('Conteúdo removido')}catch(e){toast(`Não foi possível remover: ${e.message}`)}};
window.removePlaylist=async id=>{const playlist=state.playlists.find(x=>x.id===id);if(playlist?.screens)return toast('Esta playlist está em uso. Troque a playlist das TVs antes de apagá-la.');if(!confirm('Excluir esta playlist?'))return;try{await api.remove('playlists',`id=eq.${id}`);state.playlists=state.playlists.filter(x=>x.id!==id);save();toast('Playlist excluída')}catch(e){toast(`Não foi possível excluir: ${e.message}`)}};
window.editPlaylist=id=>openPlaylist(state.playlists.find(x=>x.id===id));
window.editScreen=id=>{const s=state.screens.find(x=>x.id===id);if(!s)return toast('TV não encontrada');modal('Configurar TV','Atribua ou troque a playlist desta TV a qualquer momento.',`<div class="field"><label>Nome</label><input id="f-name" maxlength="80" value="${esc(s.name)}"></div><div class="field"><label>Local</label><input id="f-location" maxlength="120" value="${esc(s.location)}"></div><div class="field"><label>Playlist exibida nesta TV</label><select id="f-playlist"><option value="">Sem playlist</option>${state.playlists.map(p=>`<option value="${esc(p.id)}" ${s.playlistId===p.id?'selected':''}>${esc(p.name)}</option>`).join('')}</select><small>Você pode criar uma playlist e voltar aqui para atribuí-la.</small></div>`,async()=>{try{await api.update('screens',`id=eq.${id}`,{name:$('#f-name').value.trim(),location:$('#f-location').value.trim(),playlist_id:$('#f-playlist').value||null,updated_at:new Date().toISOString()});state=await loadCloudState();save();closeModal();toast('Programação da TV atualizada')}catch(e){toast(`Não foi possível atualizar: ${e.message}`)}})};

document.addEventListener('click',event=>{
  const button=event.target.closest('[data-card-action]');if(!button)return;
  const actions={'edit-screen':window.editScreen,'remove-screen':window.removeScreen,'edit-playlist':window.editPlaylist,'remove-playlist':window.removePlaylist,'remove-media':window.removeMedia};
  actions[button.dataset.cardAction]?.(button.dataset.id);
});

let screenFilter='all',mediaFilter='all';
function applyScreenFilters(){const term=$('#screen-search').value.trim().toLowerCase();$$('#screens-grid .screen-card').forEach(card=>card.hidden=!(card.dataset.search.includes(term)&&(screenFilter==='all'||String(screenFilter==='online')===card.dataset.online)))}
function applyMediaFilters(){const term=$('#media-search').value.trim().toLowerCase();$$('#media-grid .media-card').forEach(card=>card.hidden=!(card.dataset.search.includes(term)&&(mediaFilter==='all'||mediaFilter===card.dataset.type)))}
$('#screen-search').oninput=applyScreenFilters;$('#media-search').oninput=applyMediaFilters;$$('[data-screen-filter]').forEach(button=>button.onclick=()=>{$$('[data-screen-filter]').forEach(x=>x.classList.toggle('active',x===button));screenFilter=button.dataset.screenFilter;applyScreenFilters()});$$('[data-media-filter]').forEach(button=>button.onclick=()=>{$$('[data-media-filter]').forEach(x=>x.classList.toggle('active',x===button));mediaFilter=button.dataset.mediaFilter;applyMediaFilters()});
async function init(){const session=await requireSession();if(!session)return;if(cloudEnabled){try{state=await loadCloudState();$('#mode-label').textContent=state.workspace.name;$('.profile strong').textContent=state.workspace.name}catch(e){toast(`Falha ao carregar sua conta: ${e.message}`)}}render();document.body.classList.remove('session-loading');if(new URLSearchParams(location.search).has('pair'))openConnect()}
init();
