import './config.js';
import { api, cloudEnabled, loadCloudState, savePlaylist, getWorkspaceId } from './supabase.js';
import { requireSession,getStoredSession,signOut } from './auth.js';

let state={screens:[],media:[],playlists:[]};
const $=(s)=>document.querySelector(s), $$=(s)=>[...document.querySelectorAll(s)];
const icon=(name)=>`<i data-lucide="${name}"></i>`;
const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const safeUrl=value=>{try{const u=new URL(value,location.origin);return ['https:','http:','blob:'].includes(u.protocol)?esc(u.href):''}catch{return ''}};

function save(){render();}
function toast(msg){$('#toast-stack').insertAdjacentHTML('beforeend',`<div class="toast">${icon('circle-check')} ${esc(msg)}</div>`);lucide.createIcons();setTimeout(()=>$('.toast')?.remove(),2800)}
function empty(title,text){return `<div class="empty">${icon('monitor')}<strong>${title}</strong><span>${text}</span></div>`}
function render(){
  const online=state.screens.filter(x=>x.online).length;
  const usedBytes=state.media.reduce((total,item)=>total+(Number(item.size)||0),0),usedMb=usedBytes/1024/1024,limitMb=1024;
  $('#usage-label').textContent=`${usedMb<10?usedMb.toFixed(1):Math.round(usedMb)} MB de 1 GB`;$('#usage-bar').style.width=`${Math.min(100,usedMb/limitMb*100)}%`;
  $('#screen-count-nav').textContent=state.screens.length; $('#online-count').textContent=online;
  $('#stat-screens').textContent=state.screens.length; $('#stat-online').textContent=`${online} online agora`;
  $('#stat-media').textContent=state.media.length; $('#stat-playlists').textContent=state.playlists.length; $('#stat-hours').textContent='5s';
  $('#recent-screens').innerHTML=state.screens.slice(0,3).map(screenRow).join('')||empty('Nenhuma tela','Conecte sua primeira TV.');
  $('#screens-grid').innerHTML=state.screens.map(screenCard).join('')||empty('Nenhuma tela','Clique em Nova tela para começar.');
  $('#media-grid').innerHTML=state.media.map(mediaCard).join('')||empty('Biblioteca vazia','Adicione uma foto ou vídeo.');
  $('#playlists-grid').innerHTML=state.playlists.map(playlistCard).join('')||empty('Nenhuma playlist','Monte sua primeira sequência.');
  const activities=[];if(state.screens[0])activities.push(['monitor-check',`${esc(state.screens[0].name)} está ${state.screens[0].online?'online':'cadastrada'}`,'Status atual']);if(state.media[0])activities.push(['upload',`${esc(state.media[0].name)} está na biblioteca`,'Conteúdo']);if(state.playlists[0])activities.push(['list-video',`${esc(state.playlists[0].name)} está pronta para uso`,'Playlist']);
  $('#activity-list').innerHTML=activities.length?activities.map(a=>`<div class="activity-item"><div class="activity-icon">${icon(a[0])}</div><div><p>${a[1]}</p><small>${a[2]}</small></div></div>`).join(''):empty('Nenhuma atividade','As atualizações do seu espaço aparecerão aqui.');
  lucide.createIcons();
}
function screenRow(s){return `<div class="screen-row"><div class="screen-thumb"></div><div><strong>${esc(s.name)}</strong><small>${esc(s.location)} · ${esc(s.playlist)}</small></div><span class="${s.online?'online':'offline'}-badge">${s.online?'Online':'Offline'}</span></div>`}
function screenCard(s){return `<article class="screen-card" data-online="${s.online}" data-search="${esc(`${s.name} ${s.location}`.toLowerCase())}"><div class="screen-preview">${icon('monitor-play')}<span class="${s.online?'online':'offline'}-badge">${s.online?'Online':'Offline'}</span></div><div class="screen-info"><h3>${esc(s.name)}</h3><p>${esc(s.location)}</p><div class="screen-meta"><span>${esc(s.playlist)}</span><span>${esc(s.seen)}</span></div><div class="card-actions"><button class="secondary" data-card-action="edit-screen" data-id="${esc(s.id)}">Configurar TV</button><button class="danger-btn" data-card-action="remove-screen" data-id="${esc(s.id)}" aria-label="Apagar TV">${icon('trash-2')}</button></div></div></article>`}
function mediaVisual(m,className='media-thumb'){const poster=m.thumbnail||(m.type==='image'?m.url:'');return `<div class="${className}" ${poster?`style="background-image:url('${safeUrl(poster)}')"`:''}>${m.type==='video'&&!poster?`<video src="${safeUrl(m.url)}#t=0.2" muted playsinline preload="metadata"></video>`:''}</div>`}
function mediaCard(m){return `<article class="media-card" data-type="${m.type}" data-search="${esc(m.name.toLowerCase())}">${mediaVisual(m)}<span class="type-chip">${icon(m.type==='video'?'video':'image')} ${m.type==='video'?'Vídeo':'Foto'}</span><div class="media-actions"><button data-card-action="remove-media" data-id="${esc(m.id)}" aria-label="Apagar conteúdo">${icon('trash-2')}</button></div><div class="media-info"><h3>${esc(m.name)}</h3><p>${m.type==='video'?'Duração automática':'Tempo definido na playlist'} · pronto para usar</p></div></article>`}
function playlistCard(p){const imgs=p.items.map(id=>{const media=state.media.find(m=>m.id===id);return media?.thumbnail||media?.url}).filter(Boolean);return `<article class="playlist-card"><div class="playlist-cover">${[0,1,2].map(i=>`<div style="background-image:url('${safeUrl(imgs[i]||'')}')"></div>`).join('')}</div><h3>${esc(p.name)}</h3><p>${p.items.length} conteúdo(s) · tempos personalizados</p><div class="playlist-foot"><span>${p.screens} tela(s) usando</span><div><button class="secondary" data-card-action="edit-playlist" data-id="${esc(p.id)}">Editar</button> <button class="danger-btn" data-card-action="remove-playlist" data-id="${esc(p.id)}" aria-label="Apagar playlist">${icon('trash-2')}</button></div></div></article>`}
function modal(title,subtitle,body,onSave,wide=false){const root=$('#modal-root');root.innerHTML=`<div class="modal ${wide?'wide':''}"><div class="modal-head"><div><h2>${title}</h2><p>${subtitle}</p></div><button class="modal-close">&times;</button></div><div class="modal-body">${body}</div><div class="modal-actions"><button class="secondary modal-close">Cancelar</button><button class="primary" id="modal-save">Salvar</button></div></div>`;root.classList.add('open');root.setAttribute('aria-hidden','false');$$('.modal-close').forEach(b=>b.onclick=closeModal);$('#modal-save').onclick=onSave;lucide.createIcons()}
function closeModal(){$('#modal-root').classList.remove('open');$('#modal-root').setAttribute('aria-hidden','true')}
function openConnect(){const paired=new URLSearchParams(location.search).get('pair');const code=paired||Math.random().toString(36).slice(2,8).toUpperCase();modal('Conectar nova tela','Abra o player na TV e use o código exibido.',`<div class="connect-steps"><div class="connect-step"><b>1</b>Na TV, acesse <strong>${location.origin}/tv</strong></div><div class="connect-step"><b>2</b>Leia o QR Code ou copie o código</div><div class="connect-step"><b>3</b>Dê um nome e escolha a playlist</div></div><div class="field"><label>Código da tela</label><input id="f-code" value="${esc(paired||'')}" placeholder="Ex.: ${code}" maxlength="6"></div><div class="field"><label>Nome desta tela</label><input id="f-name" maxlength="80" placeholder="Ex.: TV da recepção"></div><div class="field"><label>Local</label><input id="f-location" maxlength="120" placeholder="Ex.: Loja Centro"></div><div class="field"><label>Playlist inicial</label><select id="f-playlist"><option value="">Sem playlist</option>${state.playlists.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('')}</select></div>`,async()=>{const name=$('#f-name').value.trim(),deviceCode=$('#f-code').value.trim().toUpperCase(),locationName=$('#f-location').value.trim()||'Novo local';if(!name||!/^[A-Z0-9]{6}$/.test(deviceCode))return toast('Informe um código válido e o nome da tela');const playlistId=$('#f-playlist').value;try{if(cloudEnabled){await api.rpc('pair_screen',{p_device_code:deviceCode,p_name:name,p_location:locationName,p_playlist_id:playlistId||null});state=await loadCloudState()}else{state.screens.push({id:Date.now()+'',code:deviceCode,name,location:locationName,online:true,playlistId,playlist:state.playlists.find(p=>p.id===playlistId)?.name||'Sem playlist',seen:'Agora'})}save();closeModal();history.replaceState({},'',location.pathname);toast('Tela conectada com sucesso')}catch(e){toast(`Não foi possível conectar: ${e.message}`)}})}
function openMedia(){
  if(!cloudEnabled)return toast('Conecte o Supabase antes de enviar arquivos');
  modal('Adicionar conteúdo','Envie uma foto ou vídeo do seu dispositivo.',`<div class="dropzone" id="upload-zone">${icon('upload-cloud')}<strong>Escolha um arquivo</strong><span>JPG, PNG, WEBP, GIF, MP4 ou WEBM · até 500 MB</span><input id="f-file" type="file" accept="image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm" hidden></div><div class="field"><label>Nome do conteúdo</label><input id="f-name" placeholder="Será preenchido com o nome do arquivo"></div><div class="setting-note">Para TVs horizontais, recomendamos imagens 1920×1080 (proporção 16:9). O ajuste final pode ser escolhido na playlist.</div><div class="upload-progress" id="upload-progress"><span></span><b>0%</b></div><div class="setting-note" id="file-status">Nenhum arquivo selecionado.</div>`,async()=>{
    const file=$('#f-file').files[0],name=$('#f-name').value.trim();
    if(!file)return toast('Selecione uma foto ou vídeo');
    const progress=value=>{const root=$('#upload-progress');root.classList.add('show');root.querySelector('span').style.width=`${value}%`;root.querySelector('b').textContent=`${value}%`};
    let uploaded=null,thumbnail=null,inserted=false;const saveButton=$('#modal-save');saveButton.disabled=true;saveButton.textContent='Enviando…';
    try{
      const type=file.type.startsWith('video/')?'video':'image';uploaded=await api.upload(file,value=>progress(Math.round(value*(type==='video' ? .82 : 1))));
      if(type==='video'){progress(84);const thumbFile=await createVideoThumbnail(file);if(thumbFile)thumbnail=await api.upload(thumbFile,value=>progress(84+Math.round(value*.16)))}
      const base={workspace_id:getWorkspaceId(),created_by:getStoredSession().user.id,name:name||file.name.replace(/\.[^.]+$/,''),type,url:uploaded.url,storage_path:uploaded.path,size_bytes:file.size,duration_seconds:10};
      try{await api.insert('media_items',{...base,thumbnail_url:thumbnail?.url||null,thumbnail_storage_path:thumbnail?.path||null});inserted=true}catch(error){if(!/thumbnail_url|thumbnail_storage_path/.test(String(error.message)))throw error;if(thumbnail?.path){await api.removeFile(thumbnail.path);thumbnail=null}await api.insert('media_items',base);inserted=true}
      progress(100);state=await loadCloudState();save();closeModal();toast('Conteúdo enviado com sucesso');
    }catch(e){if(!inserted){if(thumbnail?.path)await api.removeFile(thumbnail.path).catch(()=>{});if(uploaded?.path)await api.removeFile(uploaded.path).catch(()=>{})}toast(`Erro no envio: ${e.message}`)}finally{if(document.body.contains(saveButton)){saveButton.disabled=false;saveButton.textContent='Salvar'}}
  });
  const zone=$('#upload-zone'),input=$('#f-file');zone.onclick=()=>input.click();input.onchange=()=>{const file=input.files[0];if(!file)return;$('#file-status').textContent=`${file.name} · ${(file.size/1024/1024).toFixed(1)} MB`;if(!$('#f-name').value)$('#f-name').value=file.name.replace(/\.[^.]+$/,'')};
}
async function createVideoThumbnail(file){return new Promise(resolve=>{const video=document.createElement('video'),url=URL.createObjectURL(file);let settled=false;video.muted=true;video.playsInline=true;video.preload='metadata';const finish=value=>{if(settled)return;settled=true;URL.revokeObjectURL(url);resolve(value)},capture=()=>{if(!video.videoWidth)return finish(null);const canvas=document.createElement('canvas'),scale=Math.min(1,640/video.videoWidth);canvas.width=Math.max(1,Math.round(video.videoWidth*scale));canvas.height=Math.max(1,Math.round(video.videoHeight*scale));canvas.getContext('2d').drawImage(video,0,0,canvas.width,canvas.height);canvas.toBlob(blob=>finish(blob?new File([blob],`${file.name.replace(/\.[^.]+$/,'')}-thumb.jpg`,{type:'image/jpeg'}):null),'image/jpeg',.82)};setTimeout(()=>finish(null),8000);video.onerror=()=>finish(null);video.onloadedmetadata=()=>{const duration=Number.isFinite(video.duration)?video.duration:1;video.currentTime=Math.min(Math.max(.1,duration/3),Math.max(.1,duration-.05))};video.onseeked=capture;video.onloadeddata=()=>{if(video.currentTime===0)capture()};video.src=url})}
function localDateTime(value){if(!value)return '';const date=new Date(value);if(Number.isNaN(date.getTime()))return '';const offset=date.getTimezoneOffset();return new Date(date.getTime()-offset*60000).toISOString().slice(0,16)}
function openPlaylistPreview(items,durations,fits){
  if(!items.length)return toast('Selecione pelo menos um conteúdo para visualizar');
  let index=0,timer;const root=document.createElement('div');root.className='playlist-preview-overlay';root.innerHTML=`<div class="playlist-preview"><div class="preview-head"><strong>Pré-visualização da playlist</strong><span id="preview-counter"></span><button aria-label="Fechar">&times;</button></div><div class="preview-stage"></div><div class="preview-note">A TV usará a mesma ordem, tempo e enquadramento.</div></div>`;document.body.appendChild(root);
  const close=()=>{clearTimeout(timer);root.querySelector('video')?.pause();root.remove()},stage=root.querySelector('.preview-stage');root.querySelector('button').onclick=close;root.onclick=e=>{if(e.target===root)close()};
  const next=()=>{clearTimeout(timer);const id=items[index++%items.length],media=state.media.find(x=>x.id===id);if(!media)return next();root.querySelector('#preview-counter').textContent=`${(index-1)%items.length+1} / ${items.length}`;stage.innerHTML='';const element=document.createElement(media.type==='video'?'video':'img');element.src=media.url;element.style.objectFit=['cover','contain','fill'].includes(fits[id])?fits[id]:'cover';element.onerror=()=>{timer=setTimeout(next,500)};if(media.type==='video'){element.autoplay=true;element.muted=true;element.playsInline=true;element.controls=true;element.onended=next}else{element.onload=()=>{timer=setTimeout(next,Math.min(3600,Math.max(1,Number(durations[id])||10))*1000)}}stage.appendChild(element)};next();
}
function openPlaylist(existing){
  const p=existing||{name:'',items:[],durations:{},fits:{},schedule:{days:[0,1,2,3,4,5,6],dailyStart:'00:00',dailyEnd:'23:59'}};let order=p.items.filter(id=>state.media.some(m=>m.id===id)),draggedId='';
  const cards=state.media.map(m=>`<div class="picker-item ${order.includes(m.id)?'selected':''}" data-id="${esc(m.id)}" data-type="${m.type}">${mediaVisual(m,'picker-thumb')}<b class="order-index"></b><p>${esc(m.name)}</p>${m.type==='image'?`<div class="picker-controls"><label class="picker-duration">Tempo <input type="number" min="1" max="3600" step="1" value="${Number(p.durations?.[m.id])||10}"> s</label><label class="picker-fit">Exibição <select><option value="cover" ${(p.fits?.[m.id]||'cover')==='cover'?'selected':''}>Preencher tela</option><option value="contain" ${p.fits?.[m.id]==='contain'?'selected':''}>Mostrar inteira</option><option value="fill" ${p.fits?.[m.id]==='fill'?'selected':''}>Esticar</option></select></label></div>`:'<small class="picker-auto">Duração automática</small>'}<span>${icon('check')}</span></div>`).join('');
  const days=[['D',0],['S',1],['T',2],['Q',3],['Q',4],['S',5],['S',6]],schedule=p.schedule||{};
  modal(existing?'Editar playlist':'Nova playlist','Organize, agende e visualize antes de publicar.',`<div class="field"><label>Nome da playlist</label><input id="f-name" maxlength="80" value="${esc(p.name)}" placeholder="Ex.: Ofertas do fim de semana"></div><div class="playlist-editor-grid"><div><div class="field"><label>Biblioteca</label><div class="media-picker">${cards}</div></div></div><div><div class="field"><label>Ordem de exibição</label><small>Arraste os itens ou use as setas.</small><div class="playlist-order" id="playlist-order"></div></div></div></div><details class="schedule-box" ${schedule.startAt||schedule.endAt?'open':''}><summary>Agendamento da campanha</summary><div class="schedule-grid"><label>Início do período<input id="schedule-start" type="datetime-local" value="${esc(localDateTime(schedule.startAt))}"></label><label>Fim do período<input id="schedule-end" type="datetime-local" value="${esc(localDateTime(schedule.endAt))}"></label><label>Horário inicial<input id="daily-start" type="time" value="${esc(schedule.dailyStart||'00:00')}"></label><label>Horário final<input id="daily-end" type="time" value="${esc(schedule.dailyEnd||'23:59')}"></label></div><div class="weekdays">${days.map(([label,value])=>`<label title="${['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'][value]}"><input type="checkbox" value="${value}" ${(schedule.days||[0,1,2,3,4,5,6]).includes(value)?'checked':''}><span>${label}</span></label>`).join('')}</div></details>`,async()=>{
    const name=$('#f-name').value.trim();if(!name)return toast('Dê um nome à playlist');if(!order.length)return toast('Selecione pelo menos um conteúdo');
    const {durations,fits}=settings(),days=$$('.weekdays input:checked').map(x=>Number(x.value));if(!days.length)return toast('Escolha pelo menos um dia da semana');
    const start=$('#schedule-start').value,end=$('#schedule-end').value;if(start&&end&&new Date(end)<=new Date(start))return toast('O fim do período deve ser posterior ao início');
    const playlist=existing||{id:'p'+Date.now(),screens:0};playlist.name=name;playlist.items=[...order];playlist.durations=durations;playlist.fits=fits;playlist.schedule={startAt:start?new Date(start).toISOString():null,endAt:end?new Date(end).toISOString():null,days,dailyStart:$('#daily-start').value||'00:00',dailyEnd:$('#daily-end').value||'23:59'};
    try{await savePlaylist(playlist);state=await loadCloudState();save();closeModal();toast('Playlist salva')}catch(e){toast(`Erro: ${e.message}`)}
  },true);
  const settings=()=>{const selected=$$('.picker-item.selected');return {durations:Object.fromEntries(selected.map(x=>[x.dataset.id,x.dataset.type==='image'?Math.min(3600,Math.max(1,Number(x.querySelector('.picker-duration input')?.value)||10)):10])),fits:Object.fromEntries(selected.map(x=>[x.dataset.id,x.dataset.type==='image'?(x.querySelector('.picker-fit select')?.value||'cover'):'cover']))}};
  const renderOrder=()=>{const root=$('#playlist-order');root.innerHTML=order.map((id,index)=>{const m=state.media.find(x=>x.id===id);return `<div class="order-row" draggable="true" data-id="${esc(id)}"><i data-lucide="grip-vertical"></i><b>${index+1}</b><div class="order-row-thumb" style="background-image:url('${safeUrl(m?.thumbnail||m?.url||'')}')"></div><span>${esc(m?.name||'Conteúdo')}</span><button data-move="up" aria-label="Subir">&uarr;</button><button data-move="down" aria-label="Descer">&darr;</button></div>`}).join('')||'<small>Selecione conteúdos na biblioteca.</small>';$$('.picker-item').forEach(card=>{const index=order.indexOf(card.dataset.id);card.classList.toggle('selected',index>=0);card.querySelector('.order-index').textContent=index>=0?index+1:''});lucide.createIcons()};
  $$('.picker-item').forEach(card=>card.onclick=e=>{if(e.target.closest('.picker-controls'))return;const id=card.dataset.id,index=order.indexOf(id);if(index>=0)order.splice(index,1);else order.push(id);renderOrder()});
  const orderRoot=$('#playlist-order');orderRoot.addEventListener('click',e=>{const button=e.target.closest('[data-move]'),row=e.target.closest('.order-row');if(!button||!row)return;const index=order.indexOf(row.dataset.id),target=button.dataset.move==='up'?index-1:index+1;if(target<0||target>=order.length)return;[order[index],order[target]]=[order[target],order[index]];renderOrder()});orderRoot.addEventListener('dragstart',e=>{const row=e.target.closest('.order-row');if(row){draggedId=row.dataset.id;e.dataTransfer.effectAllowed='move'}});orderRoot.addEventListener('dragover',e=>{if(e.target.closest('.order-row'))e.preventDefault()});orderRoot.addEventListener('drop',e=>{const target=e.target.closest('.order-row');if(!target||!draggedId||target.dataset.id===draggedId)return;e.preventDefault();const from=order.indexOf(draggedId),to=order.indexOf(target.dataset.id);order.splice(to,0,order.splice(from,1)[0]);draggedId='';renderOrder()});
  $('.modal-actions').insertAdjacentHTML('afterbegin','<button class="secondary" id="playlist-preview">Pré-visualizar</button>');$('#playlist-preview').onclick=()=>{const {durations,fits}=settings();openPlaylistPreview(order,durations,fits)};renderOrder();
}
function openSettings(){modal('Minha conta','Dados do seu acesso ao TelaViva.',`<div class="field"><label>E-mail</label><input value="${esc(getStoredSession()?.user?.email||'')}" disabled></div><div class="field"><label>Plano atual</label><input value="${esc(state.workspace?.plan||'Starter')}" disabled></div><div class="setting-note">Seus dados e conteúdos são isolados dos demais clientes por políticas de segurança no banco.</div><br><button class="danger-btn" id="logout-button">Sair da conta</button>`,()=>closeModal());$('#logout-button').onclick=signOut}
$$('.nav-item[data-view]').forEach(b=>b.onclick=()=>{const id=b.dataset.view;$$('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(x=>x.classList.remove('active'));$(`#view-${id}`).classList.add('active');$('.sidebar').classList.remove('open');location.hash=id});
$$('[data-action="connect"]').forEach(b=>b.onclick=openConnect);$$('[data-action="media"]').forEach(b=>b.onclick=openMedia);$$('[data-action="playlist"]').forEach(b=>b.onclick=()=>openPlaylist());$$('[data-goto]').forEach(b=>b.onclick=()=>document.querySelector(`[data-view="${b.dataset.goto}"]`).click());$('#settings-btn').onclick=openSettings;$('.mobile-menu').onclick=()=>$('.sidebar').classList.toggle('open');
window.removeScreen=async id=>{if(!confirm('Remover esta TV?'))return;try{if(cloudEnabled)await api.remove('screens',`id=eq.${id}`);state.screens=state.screens.filter(x=>x.id!==id);save();toast('TV removida')}catch(e){toast(`Não foi possível remover: ${e.message}`)}};
window.removeMedia=async id=>{if(!confirm('Remover este conteúdo?'))return;try{const media=state.media.find(x=>x.id===id);if(cloudEnabled){if(media?.storagePath)await api.removeFile(media.storagePath);if(media?.thumbnailPath)await api.removeFile(media.thumbnailPath);await api.remove('media_items',`id=eq.${id}`)}state.media=state.media.filter(x=>x.id!==id);save();toast('Conteúdo removido')}catch(e){toast(`Não foi possível remover: ${e.message}`)}};
window.removePlaylist=async id=>{const playlist=state.playlists.find(x=>x.id===id);if(playlist?.screens)return toast('Esta playlist está em uso. Troque a playlist das TVs antes de apagá-la.');if(!confirm('Excluir esta playlist?'))return;try{await api.remove('playlists',`id=eq.${id}`);state.playlists=state.playlists.filter(x=>x.id!==id);save();toast('Playlist excluída')}catch(e){toast(`Não foi possível excluir: ${e.message}`)}};
window.editPlaylist=id=>openPlaylist(state.playlists.find(x=>x.id===id));
window.editScreen=id=>{const s=state.screens.find(x=>x.id===id);if(!s)return toast('TV não encontrada');modal('Configurar TV','Atribua ou troque a playlist desta TV a qualquer momento.',`<div class="field"><label>Nome</label><input id="f-name" maxlength="80" value="${esc(s.name)}"></div><div class="field"><label>Local</label><input id="f-location" maxlength="120" value="${esc(s.location)}"></div><div class="field"><label>Playlist exibida nesta TV</label><select id="f-playlist"><option value="">Sem playlist</option>${state.playlists.map(p=>`<option value="${esc(p.id)}" ${s.playlistId===p.id?'selected':''}>${esc(p.name)}</option>`).join('')}</select><small>Você pode criar uma playlist e voltar aqui para atribuí-la.</small></div><div class="setting-note">Ao desvincular, esta TV receberá automaticamente um QR Code novo.</div>`,async()=>{try{await api.update('screens',`id=eq.${id}`,{name:$('#f-name').value.trim(),location:$('#f-location').value.trim(),playlist_id:$('#f-playlist').value||null,updated_at:new Date().toISOString()});state=await loadCloudState();save();closeModal();toast('Programação da TV atualizada')}catch(e){toast(`Não foi possível atualizar: ${e.message}`)}});$('.modal-actions').insertAdjacentHTML('afterbegin','<button class="danger-btn" id="screen-unlink">Desvincular e gerar novo QR</button>');$('#screen-unlink').onclick=async()=>{if(!confirm('Desvincular esta TV e gerar um QR Code novo?'))return;try{await api.remove('screens',`id=eq.${id}`);state=await loadCloudState();save();closeModal();toast('TV desvinculada. O novo QR aparecerá em alguns segundos.')}catch(e){toast(`Não foi possível desvincular: ${e.message}`)}}};

document.addEventListener('click',event=>{
  const button=event.target.closest('[data-card-action]');if(!button)return;
  const actions={'edit-screen':window.editScreen,'remove-screen':window.removeScreen,'edit-playlist':window.editPlaylist,'remove-playlist':window.removePlaylist,'remove-media':window.removeMedia};
  actions[button.dataset.cardAction]?.(button.dataset.id);
});

let screenFilter='all',mediaFilter='all';
function applyScreenFilters(){const term=$('#screen-search').value.trim().toLowerCase();$$('#screens-grid .screen-card').forEach(card=>card.hidden=!(card.dataset.search.includes(term)&&(screenFilter==='all'||String(screenFilter==='online')===card.dataset.online)))}
function applyMediaFilters(){const term=$('#media-search').value.trim().toLowerCase();$$('#media-grid .media-card').forEach(card=>card.hidden=!(card.dataset.search.includes(term)&&(mediaFilter==='all'||mediaFilter===card.dataset.type)))}
$('#screen-search').oninput=applyScreenFilters;$('#media-search').oninput=applyMediaFilters;$$('[data-screen-filter]').forEach(button=>button.onclick=()=>{$$('[data-screen-filter]').forEach(x=>x.classList.toggle('active',x===button));screenFilter=button.dataset.screenFilter;applyScreenFilters()});$$('[data-media-filter]').forEach(button=>button.onclick=()=>{$$('[data-media-filter]').forEach(x=>x.classList.toggle('active',x===button));mediaFilter=button.dataset.mediaFilter;applyMediaFilters()});
async function init(){const session=await requireSession();if(!session)return;if(cloudEnabled){try{state=await loadCloudState();$('#mode-label').textContent=state.workspace.name;$('.profile strong').textContent=state.workspace.name}catch(e){toast(`Falha ao carregar sua conta: ${e.message}`)}}render();document.body.classList.remove('session-loading');if(new URLSearchParams(location.search).has('pair'))openConnect()}
init();
